#!/usr/bin/env python
# -*- coding: utf-8 -*-

cadena_lit = "la casa de mi mamá"
cadena_fon = "la kasa de mi mama"
cadena_cvc = "cv cvcv cv cv cvcv"

lista_pal= cadena_lit.split()
n_de_pal_listapal = len(lista_pal)
lista_cvc = cadena_cvc.split()
n_de_pal_cvc = len(lista_cvc)

lista_n_de_silabas = []

for a in (lista_cvc):
    n_v = a.count("v")
    if n_v == 1:
        print("Monoooo")
    elif n_v >= 3:
        print("Polisílabo!!!! Posible esdrújula")
    elif n_v == 2:
        print("Bisílabo")
    print(a,n_v)
    lista_n_de_silabas.append(n_v)

print(lista_pal)
print(lista_cvc)
print(n_de_pal_listapal)
print(lista_n_de_silabas)

dic_pal_estrSil = dict(zip(lista_pal,lista_cvc))
dic_pal_estrNsil = dict(zip(lista_pal,lista_n_de_silabas))

print(dic_pal_estrSil)
print(dic_pal_estrNsil)
